project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Coral Bleaching"
  author:
    - Noor Wahle (NEW2133)
    - Caterina Almazan (CGA2133)
  repo-url: https://github.com/wahlen21/coral_bleaching
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


