# Interactive graph

## Global Coral Bleaching Severity Map
```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(jsonlite)

# Load the data from the Excel file
coral_data <- read_excel("CoralBleaching.xlsx")

# Subset the data for the specified COUNTRY
subset_data <- coral_data |>
  select(LAT, LON, BLEACHING_SEVERITY, LOCATION, MONTH, YEAR, DEPTH, CORAL_FAMILY, CORAL_SPECIES, PERCENTAGE_AFFECTED, BLEACHING_DURATION, MORTALITY, RECOVERY, SURVEY_TYPE, SURVEY_AREA, WATER_TEMPERATURE, OTHER_FACTORS, REMARKS, SOURCE)

# Convert the data into a JSON object for passing to JS
json_data <- toJSON(subset_data, pretty = TRUE)
```


```{=html}
<div id="map" style="width: 100%; height: 600px;"></div>


<!-- Leaflet CSS -->
<link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
<!-- Leaflet JS -->
<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>

<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
<script src="scripts/myscript.js"></script>

<script>
// Pass the JSON data from R to the D3 script in myscript.js
let coralData = `r {{ json_data }}`;
</script>
```

<p></p>
<p></p>

## Usage
This interactive heatmap visualizes coral bleaching severity across various locations, using a color-coded system to represent different levels of bleaching. The map overlays geospatial data points based on latitude and longitude, with each point's color indicating the severity of bleaching. Bleaching severity ranges across "No Bleaching", "Low", "Medium", and "High". Users can hover over or click on data points to view additional information if available for the observation, such as the location, collection date, coral species, depth, and environmental conditions. This interactive heatmap provides a more detailed and informative experience than a static 2D map by allowing users to access specific data points directly. This tool allows users to analyze patterns in coral bleaching and related factors, enhancing their understanding of coral health across diverse regions.




